version: '3.8'

services:
  redis:
    image: redis:7.0.5

  minio:
    image: minio/minio:RELEASE.2022-11-26T22-43-32Z

  grafana:
    image: grafana/grafana:9.3.1

  nginx:
    image: nginx:1.22.1
    depends_on:
      - django
      - grafana
      - minio
  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11
    depends_on:
      - nginx

  redis-exporter:
    image: oliver006/redis_exporter:v1.45.0
    depends_on:
      - redis

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.11.0
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v2.40.6
    depends_on:
      - nginx

  django:
    build: app:latest
    depends_on:
      - postgres

  celery:
    build: app:latest
    restart: always
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:14

  backup:
    image: offen/docker-volume-backup:v2
    depends_on:
      - minio
  
  minio-manager:
    image: minio/mc:RELEASE.2022-12-02T23-48-47Z
    depends_on:
      - minio
