version: '3.8'

services:
  server:
    build: ./src
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/
    ports:
      - 7755:8000
    depends_on:
      - postgres

  celery:
    build: ./src
    command: celery -A config worker --beat --task-events -l info
    volumes:
      - ./src:/app/
    depends_on:
      - redis

  redis:
    image: redis:7.0.5
    restart: always
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres_store:/var/lib/postgresql/data
    ports:
      - "5544:5432"
    env_file:
      - ./src/dev.env

volumes:
  postgres_store:
    external: True
  redis:
    external: False