version: '3.8'

services:
  django:
    container_name: django
    build: ./src
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/
    ports:
      - 7755:8000
    depends_on:
      - postgres
    env_file:
      - ./src/dev.env

  celery:
    container_name: celery
    build: ./src
    restart: always
    command: celery -A config worker --beat --task-events -l info
    volumes:
      - ./src:/app/
    depends_on:
      - redis
    env_file:
      - ./src/dev.env

  redis:
    container_name: redis
    image: redis:7.0.5
    restart: always
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    volumes:
      - database_acus:/var/lib/postgresql/data
    ports:
      - "5544:5432"
    env_file:
      - ./src/dev.env

volumes:
  redis:
    external: False
  database_acus: