global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus_master"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'nginx_status'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ["minio:9001"]

  - job_name: redis_exporter
    static_configs:
    - targets: ['redis-exporter:9121']

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]